### ISSUE TITLE
使用过程中报错

### ISSUE THREAD

**Issue by zby1234** [DIYgod/Weibo2RSS#1]
OS ubuntu 14.04
node v6.11.0
npm 3.10.10

安装完成后可以正常运行，一段时间后报错
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 119.29.171.60:443
    at Object.exports._errnoException (util.js:1014:11)
    at exports._exceptionWithHostPort (util.js:1037:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
请问要怎么解决呢？

**Comment by DIYgod** [comment]
不知道，用pm2部署试试

**Comment by zby1234** [comment]
@DIYgod 作者您好！
我尝试过npm cache clean，重装过nodejs和npm到最新版本，还给网站安装了ssl安全证书，问题没有解决。
忘记说了程序是安装在VULTR日本节点的VPS上的，网站用apache代理了node的端口，使用inoreader RSS阅读器获取的微博(保加利亚的IP)。
查了下IP 119.29.171.60:443 是广州腾讯的云服务器，难道是这中间的网络出现了问题？
http://t.cn/RS1AyCF
我再去尝试下用PM2部署

**Comment by DIYgod** [comment]
这行去掉试试 https://github.com/DIYgod/Weibo2RSS/blob/master/routes/all.js#L4

**Comment by zby1234** [comment]
感谢！去掉了那行代码并用PM2运行，目前没有发现这个问题了
